### PR TITLE
Refactor method post_message via messages

### PR DESCRIPTION
**Pull request by abtris**
- update docs about Slack, Hipchat

### CODE REVIEW

**Comment by abtris** [comment]
@Almad @honzajavorek Please look if is ok and we publish new bb with Slack support.

**Comment by honzajavorek** [comment]
@abtris Looks good. Would you mind to add the docs mentioned in https://github.com/apiaryio/black-belt/pull/83#issuecomment-95890298?

**Comment by abtris** [comment]
@Almad Can you specify missing documentation for Slack. I don't find anything relevant for hipchat. Thanks

**Comment by honzajavorek** [comment]
@abtris I'm sorry, commenting too early in the morning :) Good to go.

**Comment by Almad** [comment]
@abtris At least on places like https://github.com/apiaryio/black-belt/blob/master/blackbelt/handle_github.py#L248

Also, when none is there, you are welcome to create one :P

**Comment by honzajavorek** [comment]
So this is what you meant - the cross docs :) I focused only on docs of the module itself. Okay, makes sense now! :+1:

**Pull request merged**
