### PR TITLE
Change default owner to anybody for schedule-list

### PR DESCRIPTION
**Pull request by abtris**

### CODE REVIEW

**Comment by fosrias** [comment]
@abtris Derp. Merged that too quickly. This would need a version bump would it not?

**Comment by Almad** [comment]
@abtris If I am reading this correctly, this would mean that without owner specified, default will be "noone assigned".

I don't like this for multiple reasons :) How about really providing our Anybody (with mention `@anybody`)  as a default assigned member?

//cc @fosrias

**Comment by abtris** [comment]
Anybody is ok. We usually create todo tasks for all team.

**Comment by Almad** [comment]
@abtris anybody as in "no member"?

Why I don't like to create those is that you can't filter on them, therefore they tend to slip through the cracks.

**Comment by fosrias** [comment]
@almad @atbris I think we could do the "Anybody", but I did find trying to
set "anybody" using the CLI switch failed, so there may be some issue with
that user from a bb standpoint.

Mark

**Comment by Almad** [comment]
@fosrias have you added the Anybody user to the work board you are mentioning?

**Comment by fosrias** [comment]
@almad @atbris No. That was probably the issues. If we make anybody the
default, need to automate adding them to the board too then.

**Comment by Almad** [comment]
@fosrias you feel like we are creating so many boards we need to automate that?

**Comment by fosrias** [comment]
Hm. I don't know. The main this is that if we plan to use "Anybody" as a
default and you have not added them manually, it messes you up. Not sure we
are adding enough, but maybe at least a better warning in bb to know what
the heck is going on vs. 400 Bad Request or 404 depending on how you spell
it, etc. Documentation is vague.

Maybe this could just be solved in the documentation of the schedule list
method to remind people the person for the --owner switch must be added to
the board. IMO, the documentation in sphinx is not useful. You have to read
the the source code cause the generated is totally confusing and worthless
for the method. To many options not pertinent to it itself. So, I would put
a comment in the source code at the least.

**Comment by Almad** [comment]
>
> Hm. I don't know. The main this is that if we plan to use "Anybody" as a
> default and you have not added them manually, it messes you up. Not sure
> we
> are adding enough, but maybe at least a better warning in bb to know what
> the heck is going on vs. 400 Bad Request or 404 depending on how you spell
> it, etc. Documentation is vague.
>
>
So is documentation of the Trello API itself :( And yes, there is basically
no error handling in bb, I think we should spent a story on it.



> Maybe this could just be solved in the documentation of the schedule list
> method to remind people the person for the --owner switch must be added to
> the board. IMO, the documentation in sphinx is not useful. You have to
> read
> the the source code cause the generated is totally confusing and worthless
> for the method. To many options not pertinent to it itself. So, I would
> put
> a comment in the source code at the least.
>
>
That's because...someone somewhere updated something and it displays the
documentation of the parent generator instead of the particular method :-o
Will take a look.

— Lukas


>
>
>
>

**Pull request merged**
