### PR TITLE
Add missing slacker

### PR DESCRIPTION
**Pull request by abtris**
We have issue after install new version `bb` missing `slacker` library.

@Almad can we add here in `pavement.py` all dependency from `requirements.txt` ?

### CODE REVIEW

**Comment by honzajavorek** [comment]
This reminds me I forgot to update `pavement.py` with the new requirements in #84. Damn Paver...

**Comment by honzajavorek** [comment]
Should fix #91

**Comment by abtris** [comment]
@honzajavorek ok, I add new dependencies from #84 too.

**Comment by honzajavorek** [comment]
Thanks! Are we waiting for @Almad or can I just say it's good to go?

**Comment by abtris** [comment]
@honzajavorek It's up to you.

**Pull request merged**
